package heuristics;

import basic.Node2D;
import java.util.*;
import java.awt.Graphics;

public interface Heuristic {

    // drawing different aspects generated by the heuristic
    void draw(Graphics g);

    List<Node2D> getHullNodes() ;
}
