package heuristics;

import basic.Node2D;
import java.awt.*;
import java.util.List;

public abstract class Heuristic {
    protected Color c;

    public Heuristic(Color c){
        this.c = c;
    }
    // drawing different aspects generated by the heuristic
    public abstract void draw(Graphics g);
    public abstract List<Node2D> getHullNodes() ;
}
